### PR TITLE
Fixes displaying with other styles than prosilver

### PR DESCRIPTION
**Pull request by Galixte**
Hi @rxu,

disable displaying for other styles:
- PBTech: https://github.com/PayBas/style-PBTech,
- PBWoW 3: https://github.com/PayBas/PBWoW3style.

It’s needed for those two particular styles.

### CODE REVIEW

**Comment by Galixte** [comment]
Hi @rxu,

could you merge this, please ?

**Comment by rxu** [comment]
Those are just empty files?

**Comment by Galixte** [comment]
Yes, because those style have already a similar system, and with those empty files, your extension do go alterate their defautt system.

**Comment by rxu** [comment]
Ah, ther're inheriting from prosilver. I see, thanks.

**Comment by Galixte** [comment]
It's ok to merge this PR ?

**Comment by rxu** [comment]
What if we won't create any files but just empty folders for the styles? Will they still use template events from prosilver?

**Comment by Galixte** [comment]
just ```styles/pbtech``` and ```/styles/pbwow3``` ?

**Comment by Galixte** [comment]
I tested your suggestion, but no with only  empty folders it doesn’t work. We have to put those empty files, sorry.

**Comment by rxu** [comment]
Thanks.

**Pull request merged**
